name:                symbiote
version:             0.0.2
github:              "athanclark/symbiote"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "2019 Athan Clark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Data serialization, communication, and operation verification implementation
category:            Data, Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/athanclark/symbiote#readme>

dependencies:
- base >= 4.7 && < 5
- abides
- aeson
- async
- bytestring
- cereal
- containers
- exceptions
- extractable-singleton
- monad-control-aligned
- mtl
- stm
- text
- QuickCheck
- quickcheck-instances
- websockets-simple >= 0.2.0
- websockets-simple-extra
- wai-transformers >= 0.1.0
- zeromq4-haskell
- zeromq4-simple >= 0.0.0.2

library:
  source-dirs: src

tests:
  symbiote-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symbiote
    - aeson
    - bytestring
    - cereal
    - http-types
    - QuickCheck
    - quickcheck-instances
    - stm
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - wai
    - wai-extra
    - wai-transformers
    - wai-websockets
    - warp
    - websockets
    - websockets-simple
